.vscode/extensions.json
.vscode/settings.json
.yarn/sdks/eslint/bin/eslint.js
.yarn/sdks/eslint/lib/api.js
.yarn/sdks/eslint/lib/unsupported-api.js
.yarn/sdks/eslint/package.json
package.json
yarn.lock

* [added vscode support for eslint](https://github.com/pagopa/io-auth-n-identity-domain/commit/9ad5253b95e9ce8c086ade69c097f0856d87dd6e)
add eslint support
vscode settings working

[#IOPID-1785] added support for eslint

---

.eslintrc.js
.vscode/settings.json
.yarnrc.yml
apps/session-manager/.eslintrc.js
apps/session-manager/package.json
apps/session-manager/tsconfig.json
package.json
packages/eslint-config-monorepo/README.md
packages/eslint-config-monorepo/index.js
packages/eslint-config-monorepo/package.json
packages/eslint-config-monorepo/react-internal.js
tsconfig.json
yarn.lock

- Add `packages/eslint-config-monorepo`
- Update session-manager eslint config for using the new package
- Rollback from pnp: we are experiencing troubles with eslint and we want to move on with development, so we postpone its usage
Monorepo setup
static checks

[#IOPID-1785]  fix eslint

---

.github/workflows/azure-deploy-session-manager.yaml

[#IOPID-1764] fix workspace name

---

.github/actions/build-workspace/action.yml
.github/workflows/azure-deploy-session-manager.yaml
.github/workflows/azure-deploy-workspace-template.yaml
.yarnrc.yml

[#IOPID-1764] Add deploy workspace and  build-workspace action

---

.github/workflows/azure-deploy-session-manager.yaml
.github/workflows/azure-deploy-workspace-template.yaml

[#IOPID-1764] tentative 2

---

.github/workflows/azure-deploy-session-manager.yaml
.github/workflows/azure-deploy-workspace-template.yaml

[#IOPID-1764]  fix temptative 3

---

infra/github-runner/prod/westeurope/.terraform.lock.hcl
infra/github-runner/prod/westeurope/README.md
infra/github-runner/prod/westeurope/container_app_job.tf
infra/github-runner/prod/westeurope/locals.tf
infra/identity/prod/westeurope/README.md

Add README
Remove temporary branch with the workaround and replace it with proper module implementation

[EC-272] Update GitHub self-hosted runner config

---

.github/workflows/azure-deploy-session-manager.yaml
.github/workflows/azure-deploy-workspace-template.yaml

Fix cd pipeline

---

infra/repository/README.md
infra/repository/locals.tf

Update variable values
Resource names are changed

[EC-274] Update variable values on GitHub repository

---

.github/workflows/code_review.yaml
turbo.json

Use local generate dependency in build
the pipeline doesn't execute the generate script

Fix generate job in turbo pipeline

---

infra/repository/locals.tf

Temporary resource for session manager created with another name
Workaround to unblock tasks

[EC-276] Update app service variable name

---

.github/workflows/code_review.yaml
apps/session-manager/package.json
apps/session-manager/tsconfig.json
package.json
turbo.json
yarn.lock

- Add `clean` step
- Add `dependency-check` test after build step
- Remove `__tests__` folder from `dist`
Improve CI and CD checks
Appinsight library has not been imported in first commit, to let the CI pipeline fails.

fix: Add clean and dependency-check scripts

---

.dockerignore
.gitignore
apps/session-manager/src/app.ts
docker-compose.yml
docker/session-manager/Dockerfile
docker/session-manager/env-dev

* [initial session-manager containerization with io-mock support](https://github.com/pagopa/io-auth-n-identity-domain/commit/15fb1732e604a49fc3fcf17ce434999eedc96684)
manual integration tests being possible
login and getsession successfully tested. make sure to read the notes inside the docker-compose

initial session-manager containerization with io-mock support

---

infra/identity/prod/westeurope/README.md
infra/identity/prod/westeurope/locals.tf
infra/identity/prod/westeurope/main.tf

Clean up useless locals
Use another identity for session manager domain
TF module has the fix about the conditional provisioning, the desired state can be now achieved

[EC-276] Setup Managed Identities for workflows

---

apps/session-manager/src/app.ts
apps/session-manager/src/controllers/index.ts
apps/session-manager/src/controllers/session.ts
apps/session-manager/src/repositories/fn-app-api.ts
apps/session-manager/src/repositories/index.ts
apps/session-manager/src/repositories/redis.ts
apps/session-manager/src/services/index.ts
apps/session-manager/src/services/profile.ts
apps/session-manager/src/services/redis-session-storage.ts

Depends on #17 
Removed single export on modules
Add index file for remap exports in Repo, Service and Controller
To handle in a more concise way ed improve the developer experience writing new methods
unit test

Proposal indexing internal deps

---

infra/repository/data.tf
infra/repository/locals.tf

- [update ARM_CLIENT_ID with new value](https://github.com/pagopa/io-auth-n-identity-domain/commit/d7d7ab1e5509476275b36f14c7643ef50333bb91)
Deploy pipeline does not have right permissions for login into Azure, after the recreation of its Managed Identity in https://github.com/pagopa/io-auth-n-identity-domain/pull/20

fix: Update `ARM_CLIENT_ID` secret with new value

---

CODEOWNERS
apps/session-manager/package.json
apps/session-manager/src/__mocks__/lollipop.mocks.ts
apps/session-manager/src/__mocks__/repositories/lollipop-api.mocks.ts
apps/session-manager/src/app.ts
apps/session-manager/src/models/domain-errors.ts
apps/session-manager/src/repositories/index.ts
apps/session-manager/src/repositories/lollipop-api.ts
apps/session-manager/src/services/__tests__/lollipop.spec.ts
apps/session-manager/src/services/index.ts
apps/session-manager/src/services/lollipop.ts
docker/session-manager/env-dev

- Add `LollipopApiClient` and its mocks
- Add `LollipopService` with `generateLCParams` and its tests
- Add `DomainErrors` for handling errors from services
Resolve common dependencies for next PRs
Unit tests

[IOPID-1842] Add `LollipopService`

---

.changeset/happy-maps-stare.md
apps/session-manager/api/fims.yaml
apps/session-manager/env.example
apps/session-manager/package.json
apps/session-manager/src/app.ts
apps/session-manager/src/auth/bearer-FIMS-token-strategy.ts
apps/session-manager/src/controllers/__tests__/sso.spec.ts
apps/session-manager/src/controllers/index.ts
apps/session-manager/src/controllers/sso.ts
apps/session-manager/src/services/__tests__/redis-session-storage.spec.ts
apps/session-manager/src/services/redis-session-storage.ts
apps/session-manager/src/types/taskEither-utils.ts
docker/session-manager/env-dev

This PR depends on https://github.com/pagopa/io-infra/pull/976
- [[#IOPID-1831] add getByFIMSToken to redis service + tests](https://github.com/pagopa/io-auth-n-identity-domain/pull/21/commits/7993717d4fa1d5d1eaedb347eb5b6a1e2e27293a)
- [[#IOPID-1831] add fims.yaml + generation](https://github.com/pagopa/io-auth-n-identity-domain/pull/21/commits/1ae81ed2d4c34f50d9909707fb2e28cad48d505c)
- [[#IOPID-1831] add new SSOController + tests](https://github.com/pagopa/io-auth-n-identity-domain/pull/21/commits/b6b2349ed2b056ebf3c7a5925beaf40abb2f84e1)
- [[#IOPID-1831] add new bearer-FIMS-token-strategy](https://github.com/pagopa/io-auth-n-identity-domain/pull/21/commits/efd8317b103b11ac1d0a618db74322316929e9c2)
- [[#IOPID-1831] mount new route + update …

[#IOPID-1831, #IOPID-1840]  Expose getFIMSToken

---

.changeset/strong-swans-applaud.md
apps/session-manager/src/repositories/fn-app-api.ts
docker/session-manager/env-dev

Missing /api/v1 on fn-app client

[#IOPID-1831] fix: set basePath as partial

---

.changeset/wicked-cups-fix.md
apps/session-manager/api/fims.yaml
apps/session-manager/src/__mocks__/lollipop.mocks.ts
apps/session-manager/src/__mocks__/services/lollipopService.mocks.ts
apps/session-manager/src/__mocks__/services/redisSessionStorageService.mocks.ts
apps/session-manager/src/app.ts
apps/session-manager/src/controllers/__tests__/sso.spec.ts
apps/session-manager/src/controllers/sso.ts
apps/session-manager/src/models/domain-errors.ts
apps/session-manager/src/services/__tests__/redis-session-storage.spec.ts
apps/session-manager/src/services/index.ts

⚠️ This PR depends on #21 IOPID-1831--add-fims-token
- [[#IOPID-1842] add new getUserForFIMSPlus endpoint](https://github.com/pagopa/io-auth-n-identity-domain/pull/27/commits/5226e39586e792c43bb05a90cf1ec1e700b3bf38)
- [[#IOPID-1842] add getUserForFimsPlus tests + small fixes](https://github.com/pagopa/io-auth-n-identity-domain/pull/27/commits/10983387333b1b9e924b4fdffbecb59fd8ecc22b)
Expose new endpoint for retrieving a FIMS+ user
unit tests, io-mock

[#IOPID-1842]  Expose `getLollipopUserForFims` endpoint

---

.changeset/kind-fireants-ring.md
apps/session-manager/src/utils/express.ts

[fix expressErrorMiddleware](https://github.com/pagopa/io-auth-n-identity-domain/commit/9c64ae1b3f5f481ff386707b99e5a81b1442bce6)
`expressErrorMiddleware` is called for each request
io-mock

fix: expressErrorMiddleware

---

.changeset/rare-horses-confess.md
apps/session-manager/src/app.ts
apps/session-manager/src/utils/network.ts

[#IOPID-1867] Fix: client IP receivance

---

apps/session-manager/package.json
apps/session-manager/src/__mocks__/appinsights.ts
apps/session-manager/src/__mocks__/repositories/queue-client.mocks.ts
apps/session-manager/src/app.ts
apps/session-manager/src/controllers/__tests__/sso.spec.ts
apps/session-manager/src/repositories/__tests__/lollipop-revoke-queue.spec.ts
apps/session-manager/src/repositories/__tests__/notifications.spec.ts
apps/session-manager/src/repositories/index.ts
apps/session-manager/src/repositories/lollipop-revoke-queue.ts
apps/session-manager/src/repositories/notifications.ts
apps/session-manager/src/services/__tests__/lollipop.spec.ts
apps/session-manager/src/services/__tests__/redis-session-storage.spec.ts
apps/session-manager/src/services/index.ts
apps/session-manager/src/services/lollipop.ts
apps/session-manager/src/services/redis-session-storage.ts
apps/session-manager/src/types/notifications.ts
apps/session-manager/src/utils/lollipop.ts
yarn.lock

Porting logic for `LollipopRevokeQueue` and `Notifications` repo
Porting `deleteAssertionRefAssociation ` in `LollipopService`
Porting `delLollipopDataForUser` in `RedisSessionStorage`
Add notifications types
We are porting in this PR some functionalities needed to implement `acs` and `logout`
unit test

[#IOPID-1866] delAssertionRef and delete installation repos and services

---

.changeset/itchy-gifts-provide.md
apps/session-manager/src/utils/__tests__/network.spec.ts
apps/session-manager/src/utils/network.ts

Fast login endpoint fails due to ip decoding error
Unit test

fix: Try decode client ip from `x-client-ip` header

---

.changeset/wicked-apes-confess.md
apps/session-manager/api/pagopa.yaml
apps/session-manager/env.example
apps/session-manager/package.json
apps/session-manager/src/app.ts
apps/session-manager/src/auth/bearer-wallet-token-strategy.ts
apps/session-manager/src/config/index.ts
apps/session-manager/src/config/pagopa.ts
apps/session-manager/src/controllers/__tests__/pagopa.spec.ts
apps/session-manager/src/controllers/index.ts
apps/session-manager/src/controllers/pagopa.ts
apps/session-manager/src/services/redis-session-storage.ts
docker/session-manager/env-dev

* [[#IOPID-1832] migrated logic of pagopa user endpoint](https://github.com/pagopa/io-auth-n-identity-domain/commit/076926f29729f2a752bc33642534bef132c0f72f)
* [[#IOPID-1832] migrated endpoint unit tests](https://github.com/pagopa/io-auth-n-identity-domain/commit/ba106dffecb4bf6f5bd5be6000555d363d195c65)
migrate pagopa user endpoint
migrated unit tests

[#IOPID-1832] pagopa user endpoint

---

.changeset/tall-bugs-kneel.md

[#IOPID-1817] Changeset to release test-login

---

.changeset/cold-snakes-trade.md
apps/session-manager/src/utils/package.ts
apps/session-manager/tsconfig.json

Change package.json import to avoid src folder

fix: Change package.json import to avoid src folder

---

.changeset/short-bobcats-play.md
apps/session-manager/env.example
apps/session-manager/src/app.ts
apps/session-manager/src/config/fims.ts
apps/session-manager/src/config/index.ts
docker/session-manager/env-dev

* [[#IOPID-1858] added whitelist for FIMS endpoints](https://github.com/pagopa/io-auth-n-identity-domain/commit/f826470d1bc8e6310b57fe696829dfdb7cd93c08)
add whitelist for fims endpoints
integration tests shows unauthorized when an out of range ip is calling a fims endpoint

[#IOPID-1858] added whitelist for FIMS endpoints

---

.changeset/tricky-wolves-allow.md
apps/session-manager/src/app.ts
apps/session-manager/src/controllers/authentication.ts
apps/session-manager/src/controllers/pagopa.ts
apps/session-manager/src/services/lollipop.ts
apps/session-manager/src/utils/appinsights.ts
apps/session-manager/src/utils/lollipop.ts

sampling is disabled for this events
* [[#IOPID-1900] add appinsights events for lollipop operations](https://github.com/pagopa/io-auth-n-identity-domain/commit/de6e5e3ea8d71325dac322547e4c5c7a3ace4fee)
align implementation with io-backend one
integration tests with an appinsights development instance

[#IOPID-1900] add appinsights events for lollipop operations

---

.changeset/hip-cows-confess.md

Release commit

---

.changeset/hip-trees-drum.md
apps/session-manager/src/app.ts
apps/session-manager/src/controllers/sso.ts
apps/session-manager/src/services/lollipop.ts
apps/session-manager/src/utils/__tests__/lollipop.spec.ts
apps/session-manager/src/utils/lollipop.ts

* [[#IOPID-2074] added missing error events during generateLCParams](https://github.com/pagopa/io-auth-n-identity-domain/commit/bb006bd655aeb2e6e7e18b4ce37c4a3a59d9f6c6)
* [[#IOPID-2074] added telemetry client on lollipopUser for FIMS endpoint](https://github.com/pagopa/io-auth-n-identity-domain/commit/ac4038a37866c9323363d30e9fec3b0df05664a5)
align error tracking with `io-backend`

[#IOPID-2074] added missing lollipop events on generateLCParams util

---

apps/session-manager/src/utils/__tests__/lollipop.spec.ts
apps/session-manager/src/utils/lollipop.ts

- optimize lollipop calls: when an error occurred, stop the call
-  return 403 when assertion is missing
Optimize fast-login call + bugfix
Unit tests

[#IOPID-2075] optimize lollipop calls, return 403 when assertion is missing

---

.changeset/clever-swans-hammer.md

[#IOPID-2075] Add changeset

---

.changeset/dirty-garlics-tell.md
apps/session-manager/api/internal.yaml
apps/session-manager/src/controllers/__tests__/session.spec.ts
apps/session-manager/src/controllers/session.ts
apps/session-manager/src/services/token.ts
apps/session-manager/src/utils/__tests__/fields-filter.spec.ts
apps/session-manager/src/utils/fields-filter.ts

* introduced an optional `filter` query param on `getSession` endpoint that enables the computation of only the selected fields
* refactored `getSessionState` handler
* async zendesk token suffix(tested with `--trace-sync-io` option for node runtime)
optimize `getSession` endpoint time execution
unit tests, manual integration tests via `docker`.

[#IOPID-2054] optimized getsession

---

.changeset/spicy-mayflies-develop.md
apps/session-manager/src/controllers/__tests__/session.spec.ts
apps/session-manager/src/controllers/session.ts

* [[#IOPID-2054] fix query parameter name](https://github.com/pagopa/io-auth-n-identity-domain/commit/0fc73954bd96a00e8000d6525265da067f4f8ea1)
wrong parameter name

[#IOPID-2054] fix query param name

---

.vscode/extensions.json
.vscode/settings.json
README.md
package.json
vitest.workspace.mts
yarn.lock

- Setup `vitest` extension on VSCode
- Run and debug unit tests manually: execute individual tests directly within VS Code. It allows you to run a specific test or the entire test suite with just a click. If any errors occur, you can use the integrated debugger to step through the code.
- View the test results: The test results are displayed in a side panel, providing immediate feedback on the success or failure of the tests. This includes details on passed, failed, or skipped tests, making it easier to identify and resolve issues.
Unit tests

[#IOPID-2159] [DX] Setup vitest extension

---

.changeset/tall-dolls-battle.md
apps/io-session-manager/env.example
apps/io-session-manager/src/app.ts
apps/io-session-manager/src/auth/local-strategy.ts
apps/io-session-manager/src/config/login.ts
apps/io-session-manager/src/config/lollipop.ts
apps/io-session-manager/src/controllers/__tests__/authentication.spec.ts
apps/io-session-manager/src/controllers/authentication.ts
apps/io-session-manager/src/services/__tests__/profile.spec.ts
apps/io-session-manager/src/services/profile.ts
apps/io-session-manager/src/utils/__tests__/fast-login.spec.ts
apps/io-session-manager/src/utils/fast-login.ts
apps/io-session-manager/src/utils/lollipop.ts
docker/io-session-manager/env-dev

* [[#IOPID-2078] removed FF_LOLLIPOP](https://github.com/pagopa/io-auth-n-identity-domain/commit/7fd3366754d7359257150d15cd1ff2fa1442841e)
* [[#IOPID-2078] removed FF_UNIQUE_EMAIL_ENFORCEMENT](https://github.com/pagopa/io-auth-n-identity-domain/commit/6856dc132cca69e94dc0a8cfa1aa94259d1f1b5c)
remove feature flags for unused or well established features
unit tests, integration tests via docker

[#IOPID-2078] remove some feature flags

---

.changeset/dirty-balloons-heal.md
apps/io-session-manager/src/app.ts
apps/io-session-manager/src/config/login.ts
apps/io-session-manager/src/controllers/__tests__/authentication.spec.ts
apps/io-session-manager/src/services/__tests__/profile.spec.ts
apps/io-session-manager/src/services/profile.ts

Removed dead code and feature flag.
Re-enabled SPID Email on new user onboarding. 
Unit tests

[#IOPID-2202] remove FF and dead-code

---

apps/io-fast-login/README.md
apps/io-fast-login/env.example
apps/io-fast-login/src/config.ts

`APPINSIGHTS_INSTRUMENTATIONKEY` is not used and is not provided by the new module. 
Remove it from fn-fast-login configuration to avoid a decoding failure during setup

[#IOPID-1451] Remove unused `APPINSIGHTS_INSTRUMENTATIONKEY` from fn-fast-login configuration

---

.changeset/strong-terms-switch.md

Test CI/CD pipelines and release

---

.changeset/strange-insects-call.md
apps/io-lollipop/api/external.yaml
apps/io-lollipop/api/internal.yaml
apps/io-lollipop/package.json
yarn.lock

[#IOPID-2461] aligned vitest version

---

apps/io-lollipop/.opex/external/env/prod/config.yaml

[#IOPID-2557] Minor fixes to previous PR

---

.changeset/clever-boxes-admire.md
apps/io-session-manager/package.json
yarn.lock

* [updated spid-commons to newest version](https://github.com/pagopa/io-auth-n-identity-domain/commit/00ee12e83ef669fd380ec7b34ab76ea1da9023ba)
updated to node20 supported version
local integration test via docker compose

[#IOPID-2582] updated spid-commons to newest version

---

.changeset/healthy-berries-vanish.md
apps/io-public/package.json

[#IOPID-2462] move monocle-ts dependency to production

---

.changeset/green-years-poke.md
apps/io-profile-async/src/main.ts

[#IOPID-2698] Init telemetryClient on main

---

.changeset/old-bags-vanish.md
apps/io-profile-async/src/functions/__tests__/expired-session-advisor.test.ts
apps/io-profile-async/src/functions/expired-session-advisor.ts
apps/io-profile-async/src/types/expired-session-advisor-queue-message.ts

`ExpiredSessionAdvisor` updates
- Update ExpiredSessionAdvisor Queue Model, added `expiredAt` parameter
- Add check on user mail validation, in case of not validated mail do not send any E-Mail

[#IOPID-2775 #IOPID-2790] Update ExpiredSessionAdvisor queue model, avoid send E-Mail on not validated address

---

.changeset/small-walls-drum.md
packages/utilities/README.md
packages/utilities/session-expire-queue-insert/__tests__/file.test.ts
packages/utilities/session-expire-queue-insert/file.ts
packages/utilities/session-expire-queue-insert/types.ts

* [[#IOPID-2776] added expiredAt field to payload](https://github.com/pagopa/io-auth-n-identity-domain/commit/813c374e7e05fff4f218d878894e83333b0a7cc3)
* [enhanced tests](https://github.com/pagopa/io-auth-n-identity-domain/commit/78a80eaaba64ecaae539a97954d857490d0f7993)
add expiredAt field support
unit tests, local run

[#IOPID-2776] expiration date support to session:expire:insert script utility

---

.changeset/funny-kings-fold.md
apps/io-profile-async/package.json
apps/io-profile-async/src/functions/__tests__/expired-session-advisor.test.ts
apps/io-profile-async/src/functions/expired-session-advisor.ts
yarn.lock

- Update `@pagopa/io-app-email-templates`
- Add expiration date parameter while building the email for the user re-engagement on expired session
To notify the users the day their sessions expired
Unit tests

[#IOPID-2794] Add expiration date in template email

---

.changeset/many-balloons-arrive.md
apps/io-session-manager/package.json
package.json
yarn.lock

bumped spid-commons

---

.changeset/nervous-jobs-occur.md
apps/io-profile/src/functions/__tests__/create-profile.test.ts
apps/io-profile/src/functions/__tests__/notice-login-email.test.ts
apps/io-profile/src/functions/create-profile.ts

[#IOPID-2838] fixed df imports

---

.changeset/curvy-pumas-hug.md
apps/io-session-manager/api/token_introspection.yaml
apps/io-session-manager/src/controllers/__tests__/session.spec.ts

Add optional property to user introspection API:
- `spid-idp`
- `session_traking_id`
Some property required in the session middleware was missing on the first release.
`spid-idp` containing the identifiers of the spid provider used to autenticate the user
`session_traking_id` used for correlation identifiers to application insights events
updated unit test

[#IOPLT-1002] Add missing optional property to user introspection API

---

.changeset/brave-clocks-look.md
apps/io-public/src/utils/healthcheck.ts

* Dispose for cosmos client after healthcheck call

Healthcheck cosmosdb fix

---

.changeset/honest-waves-shake.md
apps/io-profile/src/utils/__tests__/healthcheck.test.ts
apps/io-profile/src/utils/healthcheck.ts

fn-profile: Dispose cosmosclient inside healthcheck

---

apps/io-session-manager-internal/api/internal.yaml

introduced token also for getSession

[#IOPID-2219] fix: token query parameter missing on getsession

---

.changeset/bright-waves-mix.md
apps/io-session-manager-internal/api/internal.yaml
apps/io-session-manager-internal/src/__mocks__/repositories/blocked-users-redis.mock.ts
apps/io-session-manager-internal/src/__mocks__/services/blocked-users-service.mock.ts
apps/io-session-manager-internal/src/controllers/__tests__/unlock-user-session.test.ts
apps/io-session-manager-internal/src/controllers/main.ts
apps/io-session-manager-internal/src/controllers/unlock-user-session.ts
apps/io-session-manager-internal/src/repositories/__tests__/blocked-users-redis.test.ts
apps/io-session-manager-internal/src/repositories/blocked-users-redis.ts
apps/io-session-manager-internal/src/repositories/redis.ts
apps/io-session-manager-internal/src/services/__tests__/blocked-users-service.test.ts
apps/io-session-manager-internal/src/services/blocked-users-service.ts

- [add BlockedUsersRedisRepository + tests](https://github.com/pagopa/io-auth-n-identity-domain/pull/296/commits/6de29085e9e059a43502dcf3eb77c1e54edf285d)
- [add BlockedUsersService + tests + mocks](https://github.com/pagopa/io-auth-n-identity-domain/pull/296/commits/3d2406c93b4e546c7d6c53f23b732eccd2b8db87)
- [add UnlockUserSessionFunction + tests + mocks](https://github.com/pagopa/io-auth-n-identity-domain/pull/296/commits/d6a00a7ec8a62d742ecc125d416aa0e3c5c41ab3)
- [expose new unlockUserSession endpoint](https://github.com/pagopa/io-auth-n-identity-domain/pull/296/commits/5e739749a4fd2c83755dce74089371579b385989)
[#IOPID-2166] Session Manager (step 2) / Introduce SessionManager Internal microservice
Unit tests

[#IOPID-2218] Expose `unlockUserSession` endpoint on SessionManager-Internal

---

.changeset/selfish-readers-suffer.md
apps/io-session-manager-internal/api/internal.yaml
apps/io-session-manager-internal/src/__mocks__/repositories/auth-lock.mock.ts
apps/io-session-manager-internal/src/__mocks__/services/session-service.mock.ts
apps/io-session-manager-internal/src/__mocks__/table-client.mock.ts
apps/io-session-manager-internal/src/controllers/__tests__/auth-lock.test.ts
apps/io-session-manager-internal/src/controllers/auth-lock.ts
apps/io-session-manager-internal/src/controllers/main.ts
apps/io-session-manager-internal/src/repositories/__tests__/auth-lock.test.ts
apps/io-session-manager-internal/src/repositories/__tests__/redis.test.ts
apps/io-session-manager-internal/src/repositories/auth-lock.ts
apps/io-session-manager-internal/src/repositories/redis.ts
apps/io-session-manager-internal/src/services/__tests__/session-service.test.ts
apps/io-session-manager-internal/src/services/session-service.ts
apps/io-session-manager-internal/src/utils/async-iterable.ts
apps/io-session-manager-internal/src/utils/errors.ts

* ported business logic and tests from io-backend
session manager pt2, io-backend internal removal
unit tests, manual integration tests

[#IOPID-2220] release auth lock endpoint

---

.changeset/dirty-oranges-hope.md
apps/io-session-manager-internal/api/internal.yaml
apps/io-session-manager-internal/src/__mocks__/services/session-service.mock.ts
apps/io-session-manager-internal/src/controllers/__tests__/auth-lock.test.ts
apps/io-session-manager-internal/src/controllers/auth-lock.ts
apps/io-session-manager-internal/src/controllers/main.ts
apps/io-session-manager-internal/src/services/__tests__/session-service.test.ts
apps/io-session-manager-internal/src/services/session-service.ts

* ported `DeleteUserSession` endpoint
session manager pt 2, porting of io-backend endpoints
unit tests, local integration tests

[#IOPID-2225] DeleteUserSession endpoint (aka logout)

---

.changeset/two-starfishes-tap.md
apps/io-session-manager-internal/api/internal.yaml

* [[#IOPID-3118] removed optional token authentication](https://github.com/pagopa/io-auth-n-identity-domain/commit/ec9d51cf0c10d3f198ce705b82fcc4815de215cf)
This was an optional authentication for a rollout plan, it isn't needed anymore

[#IOPID-3118] removed optional token authentication

---

.changeset/yellow-pianos-laugh.md
apps/io-session-manager/src/controllers/__tests__/authentication.spec.ts
apps/io-session-manager/src/controllers/authentication.ts

[#IOPID-3126] additional custom event property

---

.changeset/eleven-hotels-drum.md
packages/io-auth-n-identity-commons/package.json
packages/io-auth-n-identity-commons/src/repositories/__tests__/auth-sessions-topic-repository.test.ts
packages/io-auth-n-identity-commons/src/types/auth-session-event.ts
yarn.lock

Fix typo and update `package.json`.
Unit tests.

Fix typo in `EventTypeEnum` declaration

---

apps/io-fast-login/package.json
apps/io-session-manager-internal/src/controllers/auth-lock.ts
yarn.lock

* [chore: updated typescript to upstream version](https://github.com/pagopa/io-auth-n-identity-domain/commit/2a60f4008f3254578e59f636a21728aadfa2074a)
* [chore: removed temporary type annotation requirement workaround](https://github.com/pagopa/io-auth-n-identity-domain/commit/69c443f7232034c4d12bf923b8562ea687bbbf83)
update typescript to upstream version
remove temporary workaround inserted in https://github.com/pagopa/io-auth-n-identity-domain/pull/341
local build passed for every app and package

chore: update typescript

---

.changeset/proud-cherries-hide.md
.changeset/sharp-oranges-sneeze.md
.changeset/shy-forks-press.md
apps/io-profile-async/src/functions/__mocks__/session-notifications-repository.mock.ts
apps/io-profile-async/src/functions/__tests__/session-notification-events-processor.test.ts
apps/io-session-manager-internal/src/controllers/auth-lock.ts
apps/io-session-manager-internal/src/services/__tests__/session-service.test.ts
apps/io-session-manager-internal/src/services/session-service.ts
packages/io-auth-n-identity-commons/src/repositories/__tests__/auth-sessions-topic-repository.test.ts
packages/io-auth-n-identity-commons/src/types/__tests__/auth-session-event.test.ts
packages/io-auth-n-identity-commons/src/types/auth-session-event.ts

`io-authn-identity-commons`:
- add the following properties into `BaseAuthSessionEvent`:
- `ts`
- add the following properties into `LoginEvent`:
- `loginType`
- `scenario`
- `idp`
- add the following properties into `LogoutEvent`:
- `scenario`
`io-session-manager-internal`:
- update web logout event emission with `scenario` and `ts`
- chore: remove unused imports
`io-prof-async`
- update `LoginEvent` and `LogoutEvent` instances in tests
It provides additional information to the session events.

[#IOPID-3192] Update auth session events properties

---

.changeset/big-phones-raise.md
apps/io-session-manager-internal/src/controllers/main.ts
apps/io-session-manager-internal/src/services/__tests__/session-service.test.ts
apps/io-session-manager-internal/src/services/session-service.ts

[emit logout event for AUTH_LOCK scenario](https://github.com/pagopa/io-auth-n-identity-domain/commit/eec7896d50f64440c312bfe789120a046a4c028f)
#IOPID-2908 Engage user with expired session
unit tests, FF

[#IOPID-3065] Emit logout event for AUTH_LOCK scenario

---

.changeset/brave-cheetahs-fry.md
apps/io-session-manager/src/app.ts
apps/io-session-manager/src/config/index.ts
apps/io-session-manager/src/config/spid.ts

prepare multiple mount for all endpoints to enable graceful switch to proxy routing
local tests

[#IOPID-3205] multiple mount for all endpoints

---

.changeset/six-papayas-hang.md
apps/io-session-manager-internal/src/services/__tests__/blocked-users-service.test.ts
apps/io-session-manager-internal/src/services/__tests__/session-service.test.ts
apps/io-session-manager-internal/src/services/blocked-users-service.ts
apps/io-session-manager-internal/src/services/session-service.ts
apps/io-session-manager-internal/src/utils/appinsights.ts
apps/io-session-manager/src/controllers/__tests__/session.spec.ts
apps/io-session-manager/src/controllers/session.ts
packages/e2e/src/index.ts

Add log on serviceBus logout event emission failure
- Add customEvent emission on logout Apis(and related, lock-session, delete) both on `session-manager` and `session-manager-internal`.
- Ported `trackEvent` function from `io-profile-async` in `session-manager-internal`, this allow to write applicationInsights customEvents
- Updated tests.

[#IOPID-3265] Add log on serviceBus logout event emission failure

---

infra/resources/modules/platform_proxy_api/session_manager.tf

[#IOPID-2210] fix: fixed conflict for existing version set

---

infra/resources/modules/platform_proxy_api/session_manager.tf

[#IOPID-2210] fix: right service url for bpd api

---

.github/workflows/call_opex_api.yml
.github/workflows/call_pr_opex_api.yml

- updated action to read the terraform version from the monorepo files
solves state snapshots read attempt using newer tf version

fix: snapshot read error during apply

---

infra/bootstrapper/README.md
infra/bootstrapper/data.tf
infra/bootstrapper/locals.tf

[CES-1137] Move GitHub secrets values to ITN KeyVault

---

apps/io-profile-async/host.json
infra/resources/prod/function_profile_async.tf

Improve ServiceBusTrigger performance
- Set `AzureFunctionsJobHost__extensions__serviceBus__maxConcurrentSession` to 100
- Set `AzureFunctionsJobHost__extensions__serviceBus__sessionIdleTimeout` to 5 seconds

Configure ServiceBusTrigger to improve throughput

---

.changeset/quiet-parrots-applaud.md
apps/io-profile-async/src/models/__tests__/session-notifications.test.ts
apps/io-profile-async/src/models/session-notifications.ts

CosmosDB 404 response on delete handling in `session-notifications` container model, this avoids throwing a `TransientError` and thus triggering unnecessary retries of the ServiceBusTrigger `SessionNotificationEventsProcessor`

[#IOPID-3289] Handling 404 in session-notification model deletion operation

---

infra/resources/prod/function_profile_async.tf
infra/resources/prod/keyvault.tf

Close CES-1132
Depends on https://github.com/pagopa/io-infra/pull/1586

[CES-1132] Migrate Funct profile secrets

---

infra/resources/modules/key_vaults/auth.tf
infra/resources/modules/key_vaults/outputs.tf

Close CES-1128
Depends on https://github.com/pagopa/io-infra/pull/1586

[CES-1128] Generate new encryption keys for storage accounts

---

.github/workflows/release_infra.yaml

Use Private Agent on Release Infrastructure

---

infra/bootstrapper/README.md
infra/bootstrapper/main.tf
infra/bootstrapper/resource_groups.tf
infra/resources/modules/iam/variables.tf
infra/resources/modules/key_vaults/outputs.tf
infra/resources/modules/storage_account_services/containers.tf
infra/resources/modules/storage_account_services/variables.tf
infra/resources/modules/storage_accounts/audit.tf
infra/resources/modules/storage_accounts/outputs.tf
infra/resources/modules/storage_accounts/variables.tf
infra/resources/prod/README.md
infra/resources/prod/iam.tf
infra/resources/prod/keyvault.tf
infra/resources/prod/resource_group.tf
infra/resources/prod/storage_accounts.tf
infra/resources/prod/tfmodules.lock.json

[IOPID-3157] Add new storage account for audit logs

---

infra/resources/modules/key_vaults/outputs.tf
infra/resources/prod/storage_accounts.tf

Depends on #429
Close IOPID-3149

[IOPID-3149] Remove version from lollipop assertion encryption scope

---

infra/resources/prod/README.md
infra/resources/prod/function_lv.tf
infra/resources/prod/kv_secrets.tf

[CES-1167] Replace secrets with KeyVault references for LV Function App

---

.changeset/fast-rats-call.md
apps/io-session-manager/api/internal.yaml
apps/io-session-manager/src/controllers/__tests__/session.spec.ts
apps/io-session-manager/src/controllers/session.ts

* [[#IOPID-3335] Introduced assertion_ref in token introspect](https://github.com/pagopa/io-auth-n-identity-domain/commit/35df2d2c35b23e11ffc6fd9ef6fd864ef9d8b2b8)
As output of RFC, this is the first step to change the management of lollipop operations through other backend projects
Unit tests, local run with containers

[#IOPID-3335] Introducing assertion_ref in token introspect

---

infra/resources/prod/README.md
infra/resources/prod/function_profile_async.tf
infra/resources/prod/kv_secrets.tf

Replace secret values with kv refs for ProfileAsync Function App

---

infra/resources/modules/storage_accounts/outputs.tf
infra/resources/prod/README.md
infra/resources/prod/kv_secrets.tf
infra/resources/prod/storage_accounts.tf

- Add connection string to KeyVault
- Add poison queue

[#IOPID-3169] Create secret

---

.github/workflows/azure-deploy-session-manager.yaml
package.json
packages/eslint-config-monorepo/package.json
turbo.json
yarn.lock

- upgraded to turbo 2 using @turbo/codemod utility
turbo major 1 is deprecated

[#IOPID-3346] turbo2 upgrade through @turbo/codemod utility

---

infra/resources/prod/README.md
infra/resources/prod/storage_accounts.tf

- Enable queue diagnostic settings

[#IOPID-3169] Enable queue diagnostic settings

---

docker/function/Dockerfile
docker/server/Dockerfile

- Update `turbo` for functions and servers `1.12.5` -> `2.5.5`
- Added installation of `openssl` to the installation step in the Dockerfile `server`

[#IOPID-3351] Fix turbo and openssl issues

---

infra/resources/modules/storage_accounts/outputs.tf
infra/resources/prod/README.md
infra/resources/prod/kv_secrets.tf
infra/resources/prod/tfmodules.lock.json

- Export maintenance storage primary connection string
- Store the maintenance storage primary connection string inside the key vault

[#IOPID-3168] Store maintenance connection string in KeyVault

---

infra/resources/prod/function_profile.tf
infra/resources/prod/locals.tf
infra/resources/prod/storage_accounts.tf

Depends on #457 
- Store the profile events queue name in a local var
- Update `io-profile` function events queue storage connection string
- Update `io-profile` function events queue name
Migration to ITN

[#IOPID-3168] Update Events Queue references

---

infra/resources/modules/platform_proxy_api/session_manager.tf
infra/resources/prod/tfmodules.lock.json

- changed module to raw resources to support source_api_id field
create revision instead of a whole new api

[#IOPID-3362] fix: resources instead of module to support source_api_id

---

infra/resources/prod/README.md
infra/resources/prod/data.tf
infra/resources/prod/servicebus_topic.tf
infra/resources/prod/tfmodules.lock.json

⚠️ Depends on https://github.com/pagopa/io-infra/pull/1618
Add permission to service bus topic for the new instance of session-manager.
The new instance of session-manager need to access to the session topic of the service bus.

[#IOPLT-1303] Grant permission to SB topic for session-manager-bis

---

.github/workflows/azure-deploy-session-manager.yaml

Add need into deploy pipeline second instance

---

.github/workflows/azure-deploy-session-manager-2.yaml

Until a new version of the DX pipeline supports multiple instances deploy we duplicate the pipeline to deploy on the first and the second Session Manager instances.

[#IOPLT-1304] Duplicate Session Manager deploy pipeline

---

infra/resources/modules/platform_proxy_api/session_manager.tf
infra/resources/prod/.terraform.lock.hcl

⚠️  depends on https://github.com/pagopa/io-auth-n-identity-domain/pull/463 and https://github.com/pagopa/io-infra/pull/1618 and https://github.com/pagopa/io-auth-n-identity-domain/pull/465

[#IOPLT-1306] routing session manager using pool zendesk

---

infra/resources/prod/locals.tf
infra/resources/prod/storage_accounts.tf

- Create queue `session-notifications-init-recovery-01` inside `iopitnauthmntst01` storage account
- Create poison queue for `session-notifications-init-recovery-01`
ITN migration

[#IOPID-3152] Create queue `session-notifications-init-recovery-01`

---

infra/resources/prod/function_profile_async.tf

Disable FF DRY_RUN in `ExpiredSessionAdvisor`, enabling the dispatch of email reminders after the user session expires

[#IOPID-3381] Disable FF DRY_RUN in ExpiredSessionAdvisor

---

infra/resources/modules/storage_accounts/outputs.tf
infra/resources/prod/README.md
infra/resources/prod/kv_secrets.tf

- Add `primary_connection_string` to `output "audit"`
- Create `resource "azurerm_key_vault_secret" "audit_st_connection_string"`
ITN migration.

[#IOPID-3160] Store audit storage account connection string in KeyVault

---

.github/workflows/code_review.yaml
apps/io-fast-login/sonar-project.properties
apps/io-lollipop/sonar-project.properties
apps/io-profile-async/sonar-project.properties
apps/io-profile/sonar-project.properties
apps/io-public/sonar-project.properties
apps/io-session-manager-internal/sonar-project.properties
apps/io-session-manager/sonar-project.properties
apps/io-web-profile/sonar-project.properties
packages/io-auth-n-identity-commons/sonar-project.properties

Sonar github action, `sonarcloud-github-action` is marked as deprecated in favour of`sonarqube-scan-action`, in this pr we are swapping and upgrading the configuration.
- Update sonar action `sonarcloud-github-action` -> `sonarqube-scan-action`
- Update `sonar-project.properties`

[#IOPID-3483] Update sonar action `sonarcloud-github-action` -> `sonarqube-scan-action`

---

.changeset/eleven-planes-look.md
apps/io-session-manager/src/controllers/__tests__/authentication.spec.ts
apps/io-session-manager/src/controllers/authentication.ts

`RELOGIN` scenario on ServiceBus login session event when an active session login is made

[IOPID-3465] `RELOGIN` scenario on ServiceBus login session event when an active session login is made
